language: c
os:
 - linux
dist: xenial

compiler: clang

install:
  - sudo apt-get update
  - sudo apt-get install build-essential check pkg-config

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build dir
  - cd build
  # run cmake; hre we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  - make test
