language: c
os:
 - linux
dist: xenial

compiler:
 - gcc

jobs:
 include:
  - name: "test clean"
    script:
     - make
     - make clean

  - name: "test cleanall"
    script:
     - make
     - make cleanall
